image: node:20

variables:
  CI: "true"

stages:
  - install
  - lint
  - build
  - deploy-staging
  - deploy-production

install:
  stage: install
  script: npm ci
  artifacts:
    paths:
      - node_modules/
  only:
    - branches
    - merge_requests
    - master

lint:
  stage: lint
  script:
    - npm run format:check
    - npm run lint
    - npm run stylelint
  only:
    - branches
    - merge_requests
  dependencies: -install

build:
  stage: build
  script:
    - npm run build -- --configuration=production
  artifacts:
    paths:
      - dist/apps/carrotsHub/browser/
  only:
    - merge_requests
    - master
  dependencies: -install

deploy-staging:
  stage: deploy-staging
  script:
    - npm ci
    - npm install -g firebase-tools
    - firebase deploy --only hosting:carrot-s-hub --token "$FIREBASE_DEPLOY_TOKEN"
  only:
    - merge_requests
  dependencies:
    - build

deploy-production:
  stage: deploy-production
  script:
    - npm install -g firebase-tools
    - firebase deploy --only hosting:morkovka --token "$FIREBASE_DEPLOY_TOKEN"
  only:
    - master
  dependencies:
    - build
