image: node:20

variables:
  CI: "true"

stages:
  - install
  - lint
  - build
  - deploy-staging
  - deploy-production

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

install:
  stage: install
  script:
    - npm ci
  artifacts:
    paths:
      - node_modules/
  only:
    - branches
    - merge_requests
    - master

lint:
  stage: lint
  script:
    - npm run format:check
    - npm run lint
    - npm run stylelint
  cache:
    key: ${CI_COMMIT_REF_SLUG}
  dependencies:
    - install
  only:
    - branches
    - merge_requests

build:
  stage: build
  script:
    - npm run build -- --configuration=production
  artifacts:
    paths:
      - dist/apps/carrotsHub/browser/
  cache:
    key: ${CI_COMMIT_REF_SLUG}
  dependencies:
    - install
  only:
    - merge_requests
    - master

deploy-staging:
  stage: deploy-staging
  script:
    - npm install -g firebase-tools
    - firebase deploy --only hosting:carrot-s-hub --token "$FIREBASE_DEPLOY_TOKEN"
  cache:
    key: ${CI_COMMIT_REF_SLUG}
  dependencies:
    - build
  only:
    - merge_requests

deploy-production:
  stage: deploy-production
  script:
    - npm install -g firebase-tools
    - firebase deploy --only hosting:morkovka --token "$FIREBASE_DEPLOY_TOKEN"
  cache:
    key: ${CI_COMMIT_REF_SLUG}
  dependencies:
    - build
  only:
    - master
